# Generated by Django 4.2.18 on 2025-02-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_customuser_chats_aichat_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(verbose_name='Date')),
                ('From', models.TimeField()),
                ('Duration', models.IntegerField()),
                ('Max Participants', models.IntegerField()),
            ],
        ),
    ]
