# Generated by Django 4.2.18 on 2025-02-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_rename_slots_slot_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='From',
        ),
        migrations.AlterField(
            model_name='slot',
            name='Date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
    ]
