# Generated by Django 4.2.18 on 2025-02-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_remove_slot_from_alter_slot_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='Date',
            new_name='game_date',
        ),
    ]
