# Generated by Django 4.2.18 on 2025-02-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_rename_date_slot_game_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='Duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='Max Participants',
            new_name='max_participants',
        ),
    ]
