# Generated by Django 4.2.18 on 2025-02-15 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_participant_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_type',
            new_name='sender',
        ),
    ]
