# Generated by Django 4.2.18 on 2025-02-21 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_agent_workflow_task_execution_agent_workflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
