# Generated by Django 4.2.18 on 2025-02-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_alter_workflow_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='description',
        ),
        migrations.AddField(
            model_name='agent',
            name='backstory',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='agent',
            name='goal',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='agent',
            name='role',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
