# Generated by Django 4.2.18 on 2025-02-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_remove_agent_description_agent_backstory_agent_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_id',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
