# Generated by Django 4.2.18 on 2025-02-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_remove_task_agent_task_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
