# Generated by Django 4.2.18 on 2025-02-23 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_alter_agent_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='authentication.agent'),
        ),
    ]
