# Generated by Django 4.2.18 on 2025-02-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_agent_next_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='next_agent',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Next Agent'),
        ),
    ]
