# Generated by Django 4.2.18 on 2025-02-24 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0030_alter_agent_next_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='next_agent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_agents', to='authentication.agent'),
        ),
    ]
