# Generated by Django 4.2.18 on 2025-02-24 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_alter_agent_next_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='next_agent',
        ),
    ]
