# Generated by Django 4.2.18 on 2025-02-24 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0032_remove_agent_next_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='next_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_agent', to='authentication.agent'),
        ),
    ]
